"""Data classes for the SPY Elliott Wave Scanner."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class PivotType(Enum):
    HIGH = "high"
    LOW = "low"


class WaveDirection(Enum):
    UP = "up"
    DOWN = "down"


class WaveDegree(Enum):
    """Elliott Wave degree labels (smallest → largest used here)."""
    MINUETTE = "minuette"
    MINUTE = "minute"
    MINOR = "minor"
    INTERMEDIATE = "intermediate"


class WaveLabel(Enum):
    """Labels for individual waves inside a count."""
    W1 = "1"
    W2 = "2"
    W3 = "3"
    W4 = "4"
    W5 = "5"
    WA = "A"
    WB = "B"
    WC = "C"


class CorrectivePattern(Enum):
    ZIGZAG = "zigzag"
    FLAT = "flat"
    TRIANGLE = "triangle"
    COMPLEX = "complex"


class AlertType(Enum):
    APPROACHING_RESISTANCE = "approaching_resistance"
    APPROACHING_SUPPORT = "approaching_support"
    INVALIDATION_WARNING = "invalidation_warning"
    DIVERGENCE_DETECTED = "divergence_detected"
    WAVE_COMPLETE = "wave_complete"
    CONFLUENCE_ZONE = "confluence_zone"


class AlertPriority(Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class DivergenceType(Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"


class SequenceClassification(Enum):
    IMPULSE_UP = "impulse_up"
    IMPULSE_DOWN = "impulse_down"
    CORRECTIVE = "corrective"
    UNCLEAR = "unclear"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Pivot:
    """A detected swing high or low."""
    type: PivotType
    price: float
    bar_index: int
    timestamp: datetime
    strength: float = 0.0  # how many bars it held as extreme


@dataclass
class Wave:
    """A single labeled wave inside a larger wave count."""
    label: WaveLabel
    start: Pivot
    end: Pivot

    @property
    def length(self) -> float:
        return abs(self.end.price - self.start.price)

    @property
    def direction(self) -> WaveDirection:
        if self.end.price > self.start.price:
            return WaveDirection.UP
        return WaveDirection.DOWN


@dataclass
class WaveCount:
    """A complete or partial Elliott Wave count."""
    waves: list[Wave] = field(default_factory=list)
    direction: WaveDirection = WaveDirection.DOWN
    degree: WaveDegree = WaveDegree.MINUETTE
    pattern_type: str = "impulse"  # "impulse" | "corrective"
    corrective_subtype: Optional[CorrectivePattern] = None
    confidence: float = 0.0  # 0.0 – 1.0
    invalidation_price: Optional[float] = None
    violations: list[str] = field(default_factory=list)

    @property
    def is_complete(self) -> bool:
        if self.pattern_type == "impulse":
            return len(self.waves) == 5
        return len(self.waves) == 3

    @property
    def current_wave_label(self) -> Optional[WaveLabel]:
        if self.waves:
            return self.waves[-1].label
        return None

    def wave_by_label(self, label: WaveLabel) -> Optional[Wave]:
        for w in self.waves:
            if w.label == label:
                return w
        return None


@dataclass
class FibLevel:
    """A single Fibonacci price level."""
    ratio: float
    price: float
    label: str  # e.g. "38.2% retracement"
    source: str = ""  # description of the swing it came from


@dataclass
class ConfluenceZone:
    """A cluster of Fibonacci levels within tolerance."""
    center_price: float
    levels: list[FibLevel] = field(default_factory=list)
    strength: int = 0  # number of levels in the cluster

    @property
    def price_range(self) -> tuple[float, float]:
        prices = [lv.price for lv in self.levels]
        return (min(prices), max(prices)) if prices else (0.0, 0.0)


@dataclass
class Divergence:
    """A detected RSI or MACD divergence."""
    type: DivergenceType
    indicator: str  # "RSI(14)", "MACD(5,13,8)", etc.
    price_pivot_1: Pivot
    price_pivot_2: Pivot
    indicator_value_1: float
    indicator_value_2: float
    bar_index_start: int
    bar_index_end: int
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Alert:
    """An alert generated by the scanner."""
    alert_type: AlertType
    priority: AlertPriority
    ticker: str
    current_price: float
    target_price: Optional[float] = None
    invalidation_price: Optional[float] = None
    message: str = ""
    wave_label: Optional[str] = None
    confidence: float = 0.0
    fib_levels: list[FibLevel] = field(default_factory=list)
    divergences: list[Divergence] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class WaveProjection:
    """Projected targets for the next expected wave."""
    next_wave: str
    primary_target: float
    alt_targets: list[float] = field(default_factory=list)
    invalidation: float = 0.0
    confidence: float = 0.0


@dataclass
class ScanResult:
    """Full output from a single scanner run."""
    ticker: str
    timestamp: datetime
    current_price: float
    wave_count: Optional[WaveCount] = None
    projection: Optional[WaveProjection] = None
    fib_levels: list[FibLevel] = field(default_factory=list)
    confluence_zones: list[ConfluenceZone] = field(default_factory=list)
    divergences: list[Divergence] = field(default_factory=list)
    alerts: list[Alert] = field(default_factory=list)
